AWSTemplateFormatVersion: '2010-09-09'
Description: Basic CloudFormation Template to create an EC2 Instance
Resources:
  CFInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: cfinstance
      ImageId: ami-02af70169146bbdd3
      SubnetId: subnet-0f4e64ce0a813bf21
      SecurityGroupIds:          
        - sg-086bbc46373ed734e
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref CFInstance
  
